#!/bin/sh

# cleanup
rm -rf obj_dir
rm -f top.vcd
echo "removed"
# run Verilator to translate Verilog into C++, including C++ testbench
verilator -Wall --cc --trace top.sv --exe top_tb.cpp

# build C++ project via make automatically generated by Verilator
echo "start build"
make -j -C obj_dir/ -f Vtop.mk Vtop
echo "end build"

# run executable simulation file
obj_dir/Vtop